import type { Metadata } from "next";
import "./globals.css";
import { Cairo, Noto_Sans } from "next/font/google";
import { VerifyOTPProvider } from "@/contexts/VerifyOTPContext";
import { VerifyOTPProvider2 } from "@/contexts/VerifyOTPContext2";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { Toaster } from "@/components/ui/sonner";

export const notoSans = Noto_Sans({
  subsets: ["latin"], // Add subsets as needed
  weight: ["400", "600", "700"], // Specify weights
  style: ["normal", "italic"], // Specify styles
});
export const cairo = Cairo({
  subsets: ["latin"], // Add subsets as needed
  weight: ["400", "600", "700"], // Specify weights
  style: ["normal"], // Specify styles
});

export const metadata: Metadata = {
  title: "save bite | home",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <VerifyOTPProvider2>
      <VerifyOTPProvider>
        <html
          dir={locale === "ar" ? "rtl" : "ltr"}
          lang={locale}
          className={locale === "en" ? notoSans.className : cairo.className}
        >
          <body
            className={`antialiased min-h-screen`}
            suppressHydrationWarning={true}
          >
            <Toaster richColors theme="light" />
            <NextIntlClientProvider messages={messages}>
              {children}
              <LanguageSwitcher />
            </NextIntlClientProvider>
          </body>
        </html>
      </VerifyOTPProvider>
    </VerifyOTPProvider2>
  );
}
